name: virtual_cursor
description: Send instruction to you cursor via Win32API.
version: 1.0.2
homepage: https://github.com/LuanRoger/virtual_cursor
repository: https://github.com/LuanRoger/virtual_cursor

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  win32: ^5.0.7
  ffi: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
